mod checkout;
mod oauth;

pub use checkout::{
    ERROR_HTML as CHECKOUT_ERROR_HTML, SUCCESS_HTML as CHECKOUT_SUCCESS_HTML, WAITING_HTML,
};
pub use oauth::{ERROR_HTML as AUTH_ERROR_HTML, SUCCESS_HTML as AUTH_SUCCESS_HTML};
