const MILLISECONDS_PER_SECOND = 1000
const MILLISECONDS_PER_MINUTE = 60 * MILLISECONDS_PER_SECOND

export const TIMING = {
  INPUT_DEBOUNCE_MS: 300,
  SCROLL_DEBOUNCE_MS: 100,
  SEARCH_DEBOUNCE_MS: 300,

  RECONNECT_INITIAL_DELAY_MS: 2 * MILLISECONDS_PER_SECOND,
  RECONNECT_MAX_ATTEMPTS: 5,
  RECONNECT_MAX_DELAY_MS: 5 * MILLISECONDS_PER_SECOND,

  TOKEN_CHECK_INTERVAL_MS: 5 * MILLISECONDS_PER_MINUTE,
  TOKEN_REFRESH_THRESHOLD_MS: MILLISECONDS_PER_MINUTE,
  AGENT_DISCOVERY_INTERVAL_MS: 30 * MILLISECONDS_PER_SECOND,
  CONTEXT_STATS_INTERVAL_MS: MILLISECONDS_PER_MINUTE,

  ARTIFACT_FETCH_TIMEOUT_MS: 30 * MILLISECONDS_PER_SECOND,
  DYNAMIC_OPTIONS_TIMEOUT_MS: 30 * MILLISECONDS_PER_SECOND,

  TOOL_EXECUTION_TIMEOUT_MS: 2 * MILLISECONDS_PER_MINUTE,

  SSE_RECONNECT_DELAY_MS: 2 * MILLISECONDS_PER_SECOND,
  SSE_MAX_RETRIES: 5,
} as const

export type TimingKey = keyof typeof TIMING
