//! Coverage for the shared trait impls generated by `__define_id_common`:
//! reference `ToDbValue`, the `PartialEq<str>` family, and `Borrow<str>`.

use std::borrow::Borrow;
use std::collections::HashSet;
use systemprompt_identifiers::{DbValue, ToDbValue, UserId};

#[test]
fn to_db_value_via_reference() {
    let id = UserId::new("user_ref");
    let r: &UserId = &id;
    assert!(matches!(r.to_db_value(), DbValue::String(s) if s == "user_ref"));
}

#[test]
fn partial_eq_with_str_slice() {
    let id = UserId::new("user_eq");
    let raw: &str = "user_eq";
    assert!(id == *raw);
    assert!(*raw == id);
    assert!(id != *"other");
}

#[test]
fn partial_eq_with_bare_str() {
    let id = UserId::new("bare");
    let s: &str = "bare";
    let bare: &str = s;
    assert_eq!(*bare, id);
    assert_eq!(id, *bare);
}

#[test]
fn borrow_str_enables_hashset_str_lookup() {
    let mut set: HashSet<UserId> = HashSet::new();
    set.insert(UserId::new("member"));
    let member = UserId::new("member");
    let borrowed: &str = member.borrow();
    assert_eq!(borrowed, "member");
    assert!(set.contains("member"));
    assert!(!set.contains("missing"));
}

#[test]
fn into_string_from_owned_and_ref() {
    let id = UserId::new("owned");
    let s: String = id.clone().into();
    assert_eq!(s, "owned");
    let r: String = (&id).into();
    assert_eq!(r, "owned");
}
