name: database
version: 0.1.0
display_name: "Database"
type: infrastructure
description: PostgreSQL database abstraction layer with type-safe query management and compile-time validation

# Must load first - provides shared functions used by other modules
weight: -100
category: core

dependencies: []

# Schema files - shared functions needed by other modules
schemas:
  - file: "schema/functions.sql"
    table: ""
    required_columns: []

tables_created: []
seeds: []

queries:
  agent:
    - 47+ query variants covering artifacts, contexts, tasks, push notifications
  ai:
    - 20+ query variants for AI requests, messages, tool calls, usage analytics
  config:
    - 15+ query variants for modules and configuration variables
  core:
    - 30+ query variants for analytics sessions, events, and statistics
  log:
    - 10+ query variants for logging operations
  mcp:
    - 12+ query variants for MCP servers and tool usage
  oauth:
    - 80+ query variants for OAuth clients, tokens, authorization codes, WebAuthn
  rag:
    - 25+ query variants for markdown content, chunks, categories, tags, search
  users:
    - 40+ query variants for user management and anonymous users

features:
  - DatabaseQueryEnum pattern for type-safe query references
  - PostgreSQL-native query execution
  - DatabaseProvider abstraction (DbPool trait)
  - Transaction support with MVCC
  - JSON row deserialization
  - Compile-time query validation
  - Zero runtime cost query selection

architecture:
  - Query files organized in crates/modules/{module}/src/queries/core/*.sql
  - PostgreSQL variants in crates/modules/{module}/src/queries/core/postgres/*.sql
  - Query mapping in crates/modules/database/src/models/queries/{module}.rs
  - DatabaseQueryEnum variants in crates/modules/database/src/models/types.rs

note: This module eliminates 47+ duplicate select_query() functions and provides 30-40% reduction in repository boilerplate
