CREATE TABLE IF NOT EXISTS analytics_report_user_sessions (
    session_id TEXT PRIMARY KEY,
    user_id VARCHAR(255),
    started_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    user_type VARCHAR(255),
    converted_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    client_id VARCHAR(255) NOT NULL,
    client_type VARCHAR(255) NOT NULL,
    request_count INTEGER NOT NULL,
    avg_response_time_ms DOUBLE PRECISION NOT NULL,
    success_rate DOUBLE PRECISION NOT NULL,
    error_count INTEGER NOT NULL,
    task_count INTEGER NOT NULL,
    message_count INTEGER NOT NULL,
    ai_request_count INTEGER NOT NULL,
    total_tokens_used INTEGER NOT NULL,
    total_ai_cost_microdollars BIGINT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    device_type VARCHAR(255),
    browser TEXT,
    os TEXT,
    country TEXT,
    region TEXT,
    city TEXT,
    preferred_locale TEXT,
    referrer_source VARCHAR(255),
    referrer_url TEXT,
    landing_page TEXT,
    entry_url TEXT,
    utm_source VARCHAR(100),
    utm_medium VARCHAR(100),
    utm_campaign VARCHAR(100),
    utm_content VARCHAR(100),
    utm_term VARCHAR(100),
    endpoints_accessed TEXT,
    fingerprint_hash TEXT,
    is_bot BOOLEAN NOT NULL,
    is_ai_crawler BOOLEAN NOT NULL,
    is_scanner BOOLEAN NOT NULL,
    is_behavioral_bot BOOLEAN NOT NULL,
    behavioral_bot_reason TEXT,
    behavioral_bot_score INTEGER NOT NULL,
    session_source VARCHAR(50),
    revoked_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_ar_user_sessions_user_id ON analytics_report_user_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_ar_user_sessions_started_at ON analytics_report_user_sessions (started_at);
CREATE INDEX IF NOT EXISTS idx_ar_user_sessions_last_activity_at ON analytics_report_user_sessions (last_activity_at);
CREATE INDEX IF NOT EXISTS idx_ar_user_sessions_fingerprint_hash ON analytics_report_user_sessions (fingerprint_hash);
