use std::sync::Arc;

use sqlx::PgPool;
use sqlx::postgres::PgPoolOptions;
use systemprompt_analytics::projection::SOURCE_DEFINITIONS;
use systemprompt_database::{Database, DbPool};
use systemprompt_identifiers::ConnectionId;
use systemprompt_runtime::reporting;

pub(crate) fn analytics_schema_sql(select: impl Fn(&str) -> bool) -> String {
    use systemprompt_extension::Extension;
    systemprompt_analytics::AnalyticsExtension
        .schemas()
        .into_iter()
        .filter(|schema| schema.table.as_deref().is_some_and(&select))
        .map(|schema| schema.sql)
        .collect::<Vec<_>>()
        .join("\n")
}

fn reporting_schema_sql() -> String {
    analytics_schema_sql(|table| {
        table.starts_with("analytics_projection_") || table.starts_with("analytics_report_")
    })
}

async fn mirror_table(admin: &PgPool, pool: &PgPool, table: &str, key: Option<&str>) {
    let columns: Vec<(String, String, bool, Option<String>)> = sqlx::query_as(
        "SELECT a.attname::text, format_type(a.atttypid,a.atttypmod), a.attnotnull, pg_get_expr(d.adbin,d.adrelid) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=to_regclass($1) AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum",
    )
    .bind(format!("public.{table}"))
    .fetch_all(admin)
    .await
    .unwrap();
    let definitions = columns
        .into_iter()
        .map(|(name, kind, required, default)| {
            let default = default
                .map(|value| {
                    if value.starts_with("nextval(") {
                        " GENERATED BY DEFAULT AS IDENTITY".to_owned()
                    } else {
                        format!(" DEFAULT {value}")
                    }
                })
                .unwrap_or_default();
            format!(
                "\"{name}\" {kind}{default}{}",
                if required { " NOT NULL" } else { "" }
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let primary_key = key.map_or_else(String::new, |key| format!(", PRIMARY KEY ({key})"));
    sqlx::query(sqlx::AssertSqlSafe(format!(
        "CREATE TABLE {table} ({definitions}{primary_key})"
    )))
    .execute(pool)
    .await
    .unwrap();
}

async fn fixture() -> (PgPool, DbPool, String) {
    let url = crate::boot::database_url().expect("PostgreSQL test URL");
    let admin = PgPool::connect(&url).await.unwrap();
    let schema = format!(
        "reporting_{}",
        ConnectionId::generate().to_string().replace('-', "_")
    );
    sqlx::query(sqlx::AssertSqlSafe(format!("CREATE DATABASE {schema}")))
        .execute(&admin)
        .await
        .unwrap();
    let options = admin.connect_options().as_ref().clone().database(&schema);
    let pool = PgPoolOptions::new()
        .max_connections(4)
        .connect_with(options)
        .await
        .unwrap();
    for source in SOURCE_DEFINITIONS {
        mirror_table(&admin, &pool, source.table, Some(source.key)).await;
    }
    // Stored messages are not a source, but the ai owner's capture file
    // maintains ai_requests.message_count from them.
    mirror_table(&admin, &pool, "ai_request_messages", Some("id")).await;
    // A user delete walks every registered purge table; mirror the ones the
    // reporting sources do not already cover so the walk finds them.
    let mut mirrored: Vec<&str> = SOURCE_DEFINITIONS.iter().map(|s| s.table).collect();
    mirrored.push("ai_request_messages");
    let purge_tables = systemprompt_extension::purge::registered_user_purge_tables()
        .map(|entry| entry.table)
        .chain(systemprompt_extension::purge::registered_orphan_sweeps().map(|sweep| sweep.table));
    let mut seen: Vec<&str> = Vec::new();
    for table in purge_tables {
        if !mirrored.contains(&table) && table != "event_outbox" && !seen.contains(&table) {
            mirror_table(&admin, &pool, table, None).await;
            seen.push(table);
        }
    }
    sqlx::raw_sql(include_str!(
        "../../../../../infra/events/schema/event_outbox.sql"
    ))
    .execute(&pool)
    .await
    .unwrap();
    sqlx::raw_sql(sqlx::AssertSqlSafe(reporting_schema_sql()))
        .execute(&pool)
        .await
        .unwrap();
    // Owner schemas install capture on fresh and upgraded databases. This
    // isolated fixture bypasses the extension installer, so install the same
    // capture definitions explicitly before exercising reporting initialization.
    for script in [
        include_str!("../../../../../infra/events/schema/reporting_capture.sql"),
        include_str!("../../../../../domain/users/schema/reporting_capture.sql"),
        include_str!("../../../../../domain/agent/schema/reporting_capture.sql"),
        include_str!("../../../../../domain/ai/schema/reporting_capture.sql"),
        include_str!("../../../../../domain/mcp/schema/reporting_capture.sql"),
        include_str!("../../../../../domain/content/schema/reporting_capture.sql"),
        include_str!("../../../../../infra/logging/schema/reporting_capture.sql"),
    ] {
        sqlx::raw_sql(script).execute(&pool).await.unwrap();
    }
    for script in [
        include_str!("../../../../../domain/users/schema/migrations/014_reporting_privacy.sql"),
        include_str!("../../../../../domain/users/schema/migrations/015_user_privacy_delivery.sql"),
        include_str!("../../../../../infra/events/schema/reporting_privacy.sql"),
        include_str!("../../../../../domain/analytics/schema/reporting_privacy.sql"),
        include_str!("../../../../../domain/agent/schema/reporting_privacy.sql"),
        include_str!("../../../../../domain/ai/schema/reporting_privacy.sql"),
        include_str!("../../../../../domain/mcp/schema/reporting_privacy.sql"),
        include_str!("../../../../../domain/content/schema/reporting_privacy.sql"),
        include_str!("../../../../../infra/logging/schema/reporting_privacy.sql"),
    ] {
        sqlx::raw_sql(script).execute(&pool).await.unwrap();
    }
    sqlx::query(systemprompt_analytics::projection::REPORTING_STATE_SEED)
        .execute(&pool)
        .await
        .unwrap();
    let pool = Arc::new(pool);
    let db = Arc::new(Database::from_pools(pool, None));
    (admin, db, schema)
}

async fn initialize_and_drain(db: &DbPool, expected_seed_facts: usize) {
    reporting::initialize(db).await.unwrap();
    assert_eq!(
        reporting::process_pending(db, 100).await.unwrap(),
        expected_seed_facts
    );
    assert_eq!(reporting::status(db).await.unwrap().pending_count, 0);
}

#[tokio::test]
async fn capture_rebuild_worker_preserve_source_reports_and_pending_failures() {
    let (admin, db, schema) = fixture().await;
    let pool = db.write_pool_arc().unwrap();
    sqlx::query("INSERT INTO users (id, name, email) VALUES ('u', 'baseline', 'u@example.test')")
        .execute(&*pool)
        .await
        .unwrap();
    sqlx::query("INSERT INTO user_sessions (session_id, user_id, landing_page, request_count, is_ai_crawler) VALUES ('human', 'u', '/', 1, false), ('crawler', 'u', '/', 1, true)")
        .execute(&*pool).await.unwrap();
    initialize_and_drain(&db, 3).await;
    assert_eq!(reporting::status(&db).await.unwrap().generation, 1);
    reporting::initialize(&db).await.unwrap();
    assert_eq!(reporting::status(&db).await.unwrap().generation, 1);
    let baseline: String =
        sqlx::query_scalar("SELECT name FROM analytics_report_users WHERE id = 'u'")
            .fetch_one(&*pool)
            .await
            .unwrap();
    assert_eq!(baseline, "baseline");
    let human_count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM analytics_report_v_clean_traffic")
            .fetch_one(&*pool)
            .await
            .unwrap();
    let crawler_count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM analytics_report_v_bot_sessions")
            .fetch_one(&*pool)
            .await
            .unwrap();
    assert_eq!((human_count, crawler_count), (1, 1));

    let mut rolled_back = pool.begin().await.unwrap();
    sqlx::query("UPDATE users SET name = 'rolled back' WHERE id = 'u'")
        .execute(&mut *rolled_back)
        .await
        .unwrap();
    rolled_back.rollback().await.unwrap();
    assert_eq!(reporting::status(&db).await.unwrap().pending_count, 0);

    sqlx::query("UPDATE users SET name = 'updated' WHERE id = 'u'")
        .execute(&*pool)
        .await
        .unwrap();
    sqlx::query("INSERT INTO ai_requests (id, request_id, user_id, context_id, provider, model, actor_kind, actor_id, cost_microdollars, input_tokens, output_tokens) VALUES ('r', 'r', 'u', 'ctx', 'test', 'model', 'job', 'test', 1234567, 5, 9)")
        .execute(&*pool).await.unwrap();
    assert_eq!(reporting::status(&db).await.unwrap().pending_count, 2);
    assert_eq!(reporting::process_pending(&db, 100).await.unwrap(), 2);
    let parity: bool = sqlx::query_scalar("SELECT (SELECT sum(cost_microdollars) FROM ai_requests) = (SELECT sum(cost_microdollars) FROM analytics_report_ai_requests)")
        .fetch_one(&*pool).await.unwrap();
    assert!(parity);
    assert!(
        reporting::status(&db)
            .await
            .unwrap()
            .last_processed_at
            .is_some()
    );

    sqlx::query("UPDATE ai_requests SET cost_microdollars = 2000000 WHERE id = 'r'")
        .execute(&*pool)
        .await
        .unwrap();
    reporting::rebuild(&db).await.unwrap();
    assert_eq!(reporting::status(&db).await.unwrap().generation, 2);
    assert_eq!(reporting::process_pending(&db, 100).await.unwrap(), 1);
    let cost: i64 = sqlx::query_scalar(
        "SELECT cost_microdollars FROM analytics_report_ai_requests WHERE id = 'r'",
    )
    .fetch_one(&*pool)
    .await
    .unwrap();
    assert_eq!(cost, 2000000);

    let mut merge = pool.begin().await.unwrap();
    sqlx::query(
        "INSERT INTO users (id, name, email) VALUES ('target', 'merged', 'target@example.test')",
    )
    .execute(&mut *merge)
    .await
    .unwrap();
    sqlx::query("UPDATE ai_requests SET user_id = 'target' WHERE user_id = 'u'")
        .execute(&mut *merge)
        .await
        .unwrap();
    sqlx::query("UPDATE user_sessions SET user_id = 'target' WHERE user_id = 'u'")
        .execute(&mut *merge)
        .await
        .unwrap();
    sqlx::query("DELETE FROM users WHERE id = 'u'")
        .execute(&mut *merge)
        .await
        .unwrap();
    merge.commit().await.unwrap();
    assert_eq!(reporting::process_pending(&db, 100).await.unwrap(), 5);
    let owners: Vec<String> = sqlx::query_scalar("SELECT user_id FROM analytics_report_ai_requests UNION SELECT user_id FROM analytics_report_user_sessions")
        .fetch_all(&*pool).await.unwrap();
    assert_eq!(owners, vec!["target"]);
    let users: Vec<String> = sqlx::query_scalar("SELECT id FROM analytics_report_users")
        .fetch_all(&*pool)
        .await
        .unwrap();
    assert_eq!(users, vec!["target"]);
    sqlx::query("UPDATE users SET id = 'renamed' WHERE id = 'target'")
        .execute(&*pool)
        .await
        .unwrap();
    assert_eq!(reporting::process_pending(&db, 100).await.unwrap(), 2);
    let ids: Vec<String> = sqlx::query_scalar("SELECT id FROM analytics_report_users ORDER BY id")
        .fetch_all(&*pool)
        .await
        .unwrap();
    assert_eq!(ids, vec!["renamed"]);
    sqlx::query("DELETE FROM ai_requests WHERE id = 'r'")
        .execute(&*pool)
        .await
        .unwrap();
    assert_eq!(reporting::process_pending(&db, 100).await.unwrap(), 1);
    let count: i64 = sqlx::query_scalar("SELECT count(*) FROM analytics_report_ai_requests")
        .fetch_one(&*pool)
        .await
        .unwrap();
    assert_eq!(count, 0);

    sqlx::query("UPDATE users SET name = 'future' WHERE id = 'renamed'")
        .execute(&*pool)
        .await
        .unwrap();
    sqlx::query("UPDATE event_outbox SET fact = jsonb_set(fact, '{version}', '2') WHERE processed_at IS NULL")
        .execute(&*pool).await.unwrap();
    assert!(reporting::process_pending(&db, 100).await.is_err());
    assert_eq!(reporting::status(&db).await.unwrap().pending_count, 1);
    sqlx::query("UPDATE event_outbox SET fact = jsonb_set(fact, '{version}', '1') WHERE processed_at IS NULL")
        .execute(&*pool).await.unwrap();
    let worker = reporting::spawn(&db).unwrap();
    tokio::time::timeout(std::time::Duration::from_secs(5), async {
        loop {
            if reporting::status(&db).await.unwrap().pending_count == 0 {
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
    })
    .await
    .unwrap();
    worker.abort();
    assert!(worker.await.unwrap_err().is_cancelled());
    let name: String =
        sqlx::query_scalar("SELECT name FROM analytics_report_users WHERE id = 'renamed'")
            .fetch_one(&*pool)
            .await
            .unwrap();
    assert_eq!(name, "future");
    pool.close().await;
    sqlx::query(sqlx::AssertSqlSafe(format!(
        "DROP DATABASE {schema} WITH (FORCE)"
    )))
    .execute(&admin)
    .await
    .unwrap();
}

#[test]
fn reporting_sql_is_accepted_by_install_time_schema_linter() {
    for (name, sql) in [
        ("analytics reporting", reporting_schema_sql().as_str()),
        (
            "outbox capture",
            include_str!("../../../../../infra/events/schema/reporting_capture.sql"),
        ),
        (
            "users capture",
            include_str!("../../../../../domain/users/schema/reporting_capture.sql"),
        ),
        (
            "agent capture",
            include_str!("../../../../../domain/agent/schema/reporting_capture.sql"),
        ),
        (
            "AI capture",
            include_str!("../../../../../domain/ai/schema/reporting_capture.sql"),
        ),
        (
            "MCP capture",
            include_str!("../../../../../domain/mcp/schema/reporting_capture.sql"),
        ),
        (
            "content capture",
            include_str!("../../../../../domain/content/schema/reporting_capture.sql"),
        ),
        (
            "logging capture",
            include_str!("../../../../../infra/logging/schema/reporting_capture.sql"),
        ),
    ] {
        systemprompt_database::services::lint_declarative_schema(sql, name)
            .unwrap_or_else(|errors| panic!("{name}: {errors:?}"));
    }
}

#[path = "reporting_privacy.rs"]
mod privacy;

#[path = "reporting_user_privacy.rs"]
mod user_privacy;

#[path = "reporting_rebuild.rs"]
mod rebuild;
